name: Build QuestJournal
on: [push, pull_request]
                      
jobs:
    build:
        runs-on: windows-latest
        continue-on-error: false
        
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: '9.x.x'

            - name: Restore dependencies
              run: dotnet restore

            - name: Download Dalamud
              run: |
                  Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
                  Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"

            - name: Build plugin
              run: |
                  dotnet build --no-restore --configuration Release --nologo

            - name: Upload a Build Artifact
              uses: actions/upload-artifact@v4
              with:
                  path: |
                      ./QuestJournal/bin/x64/Release/*
